"""40 chess-relevant demo skills for routing tests + the project presentation.

Each entry: (slug, description, when, steps, constraint).
- description = the routing trigger ("Use when ..."); routing keys on THIS.
- when/steps/constraint = the SKILL.md body the model follows after load_skill.
- steps reference REAL backend tools: board_state, eval, best_move, review_move,
  threats, legal_moves, list_pieces, ask_chessbot, move, undo.
Data only — `_generate.py` renders these into <slug>/SKILL.md files.
"""
from __future__ import annotations

SKILLS: list[tuple[str, str, str, tuple[str, str, str], str]] = [
    ("opening-repertoire",
     "Use when the user asks what to open with, wants a repertoire, or how to meet a first move.",
     "the user asks what to play in the opening or wants a repertoire.",
     ("Call board_state to read the moves played so far.",
      "Ask ask_chessbot for a principled line that fits the position.",
      "Name the one middlegame plan the opening aims for."),
     "suggest only legal, principled moves; do not invent forced theory."),
    ("endgame-technique",
     "Use when the position is an endgame and the user wants to convert a win or hold a draw.",
     "few pieces remain and the user asks how to finish or hold the game.",
     ("Call board_state to confirm material and whose move it is.",
      "Use best_move with series to read the winning or holding line.",
      "Name the technique and its key idea."),
     "verify the line with the engine before promising a result."),
    ("tactics-trainer",
     "Use when the user wants to find or train tactics — forks, pins, skewers, combinations.",
     "the user asks if there is a tactic or wants tactic practice.",
     ("Call threats to see what is hanging for either side.",
      "Use best_move top=3 to surface forcing candidates.",
      "Explain the tactical motif in one line."),
     "only call a tactic sound if the engine line confirms it."),
    ("blunder-check",
     "Use when the user wants to know if their last move was a blunder or mistake.",
     "the user asks whether the move they just played was bad.",
     ("Call review_move to grade the last move against the best.",
      "Report the label and the centipawn delta.",
      "If it was a blunder, name the move that refutes it."),
     "do not guess the grade; use the review_move output."),
    ("position-evaluator",
     "Use when the user asks who is better, by how much, or to assess the position.",
     "the user asks for an evaluation of the current position.",
     ("Call eval to get the engine score from White's POV.",
      "Translate the score into plain advantage terms.",
      "Name the one factor driving the evaluation."),
     "report the sign and size as the engine gives it; do not inflate."),
    ("threat-scanner",
     "Use when the user asks what the opponent is threatening or if anything is hanging.",
     "the user asks about the opponent's threats or hanging pieces.",
     ("Call threats to see the opponent's strongest reply.",
      "State whether the threat is serious by the eval swing.",
      "Suggest one move that meets it."),
     "report 'none significant' honestly when threats says so."),
    ("mate-finder",
     "Use when the user asks if there is a forced checkmate or a mating attack.",
     "the user asks whether a forced mate exists.",
     ("Call best_move to see if the engine reports a mate score.",
      "If mate exists, give the first move and the mate distance.",
      "If not, say so and give the best practical try."),
     "only claim mate when the engine returns an M-score."),
    ("pawn-structure",
     "Use when the user asks about pawn chains, islands, doubled, backward, or passed pawns.",
     "the user asks about the pawn structure or a pawn weakness.",
     ("Call board_state with fields=fen to read the pawn skeleton.",
      "Ask ask_chessbot to name the structure and its plans.",
      "Point out the one pawn that decides the plan."),
     "describe only pawns present in the position."),
    ("king-safety",
     "Use when the user asks how exposed a king is or whether to castle.",
     "the user asks about king safety or castling.",
     ("Call board_state to see castling rights and check status.",
      "Call threats to test if the king is under real pressure.",
      "Recommend castle, hold, or shelter the king."),
     "weigh safety against tempo; do not castle into an attack."),
    ("piece-activity",
     "Use when the user wants to improve a passive piece or find their worst-placed piece.",
     "the user asks which piece to improve or how to activate one.",
     ("Call list_pieces to see where each piece stands.",
      "Identify the least active piece and a better square.",
      "Give the move that reroutes it."),
     "improve the worst piece first; keep the move legal."),
    ("opening-trap-spotter",
     "Use when the user worries about an opening trap or gambit they might fall into.",
     "the user asks if a line is a trap or how to avoid one.",
     ("Call board_state to read the exact move order.",
      "Ask ask_chessbot whether a known trap lurks here.",
      "Give the safe move that sidesteps it."),
     "do not enter a line you cannot refute over the board."),
    ("clock-strategy",
     "Use when the user asks about time management, time trouble, or how fast to play.",
     "the user asks how to handle the clock or time pressure.",
     ("Ask ask_chessbot for time-management guidance for the phase.",
      "Tell the user where to spend time and where to move fast.",
      "Give one rule to avoid flagging."),
     "advise on time use only; do not fabricate the clock reading."),
    ("move-explainer",
     "Use when the user asks why a specific move is good, bad, or what it accomplishes.",
     "the user asks to explain the point of a move.",
     ("Call eval and reason about the move's idea.",
      "Use review_move if the move was already played.",
      "Explain the purpose in one coaching sentence."),
     "ground the explanation in the engine output, not vibes."),
    ("candidate-moves",
     "Use when the user wants a shortlist of the best moves to consider.",
     "the user asks for candidate moves or the top options.",
     ("Call best_move with top=3 to list the leading moves.",
      "Order them by the engine score.",
      "Add a one-line idea for the top choice."),
     "list only engine-supported candidates with their scores."),
    ("middlegame-plan",
     "Use when the user asks what the plan is or what to aim for in the middlegame.",
     "the user asks for a plan in a middlegame position.",
     ("Call eval and board_state to read the imbalances.",
      "Pick the side of the board where you are stronger.",
      "State a concrete three-move plan."),
     "tie the plan to the actual imbalances on the board."),
    ("weak-square-finder",
     "Use when the user asks about weak squares, holes, or outpost targets.",
     "the user asks where the weak squares or holes are.",
     ("Call board_state with fields=fen to map the pawns.",
      "Find squares no enemy pawn can defend.",
      "Name the piece that should occupy the best hole."),
     "a hole must be a square no pawn can ever cover."),
    ("material-counter",
     "Use when the user asks who is up material or what the material balance is.",
     "the user asks about the material count or who is ahead in material.",
     ("Call list_pieces color=mine and color=theirs.",
      "Sum the standard piece values for each side.",
      "Report the net material difference."),
     "count only pieces on the board right now."),
    ("legal-move-helper",
     "Use when the user asks which moves are legal for a piece or from a square.",
     "the user asks what a piece can legally do.",
     ("Call legal_moves with the square in question.",
      "List the legal destinations clearly.",
      "Flag any that walk into a tactic."),
     "report only moves legal_moves returns."),
    ("fork-finder",
     "Use when the user wants to find a fork — one piece attacking two targets at once.",
     "the user asks if there is a fork available.",
     ("Call threats and best_move top=3 to spot double attacks.",
      "Check whether a knight or queen hits two targets.",
      "Give the forking move and what it wins."),
     "confirm both targets are real before calling it a fork."),
    ("pin-detector",
     "Use when the user asks about pins — a piece stuck in front of a more valuable one.",
     "the user asks whether a pin exists or how to exploit one.",
     ("Call board_state with fields=fen to see the alignment.",
      "Identify the pinned piece and the piece behind it.",
      "Suggest how to pile on the pinned piece."),
     "verify the line of the pin on the actual board."),
    ("discovered-attack",
     "Use when the user asks about discovered attacks or discovered checks.",
     "the user asks if moving a piece uncovers an attack.",
     ("Call best_move top=3 to find moves that unveil a threat.",
      "Identify the front piece and the unmasked attacker.",
      "Give the move and what the discovery wins."),
     "ensure the moving piece itself stays safe or gains tempo."),
    ("zwischenzug-coach",
     "Use when the user asks about in-between moves before recapturing.",
     "the user asks whether an in-between move beats the obvious recapture.",
     ("Call best_move to compare the recapture with alternatives.",
      "Look for a more forcing reply that improves the order.",
      "Show the zwischenzug and why it gains."),
     "the in-between move must be more forcing than the recapture."),
    ("sacrifice-evaluator",
     "Use when the user wants to know if a sacrifice is sound.",
     "the user asks whether giving up material works here.",
     ("Call eval on the position after the sacrifice.",
      "Use best_move series to read the follow-up line.",
      "Say sound or unsound with the reason."),
     "call a sac sound only if the engine line supports it."),
    ("defense-advisor",
     "Use when the user is worse and asks how to defend or hold.",
     "the user asks how to survive a worse or losing position.",
     ("Call threats to find the most dangerous idea.",
      "Use best_move to find the toughest defensive resource.",
      "Recommend the move that creates the most problems."),
     "prefer active defense the engine backs over passive hope."),
    ("opening-principles",
     "Use when a beginner asks about basic opening rules — development, center, castling.",
     "the user asks for beginner opening guidance.",
     ("Call board_state to see how development stands.",
      "Check center control, development, and king safety.",
      "Give the one principle the position needs most."),
     "teach the principle that fits this position, not a generic list."),
    ("trade-advisor",
     "Use when the user asks whether to trade pieces or which trade favors them.",
     "the user asks if they should exchange pieces.",
     ("Call eval and reason about the resulting structure.",
      "Decide if the trade helps your plan or the opponent's.",
      "Recommend trade or keep tension with the reason."),
     "trade when it improves your position, not by default."),
    ("initiative-coach",
     "Use when the user asks how to seize the initiative or keep an attack going.",
     "the user asks how to take or keep the initiative.",
     ("Call threats to see who is forcing whom.",
      "Use best_move to find the most forcing continuation.",
      "Give the move that keeps the opponent reacting."),
     "spend tempo on forcing moves the engine rates highly."),
    ("prophylaxis-coach",
     "Use when the user wants to stop the opponent's plan before pushing their own.",
     "the user asks how to prevent the opponent's idea.",
     ("Call threats to learn the opponent's best plan.",
      "Find the move that takes that idea away.",
      "Explain what you prevented and your follow-up."),
     "address the real threat threats reports, not an imagined one."),
    ("rook-endgame",
     "Use when the position is a rook endgame needing technique like Lucena or Philidor.",
     "a rook endgame arises and the user asks how to win or draw it.",
     ("Call board_state to confirm pawns, rooks, and king places.",
      "Use best_move series to find the technical line.",
      "Name the method (Lucena, Philidor, active rook)."),
     "verify the drawing or winning method with the engine line."),
    ("opposition-coach",
     "Use when the user asks about king opposition in a pawn endgame.",
     "the user asks about the opposition or king-and-pawn technique.",
     ("Call board_state to read the king and pawn squares.",
      "Use best_move to find the move that takes the opposition.",
      "Explain who holds the opposition and why it matters."),
     "the king move must follow the engine's drawing or winning line."),
    ("perpetual-check",
     "Use when the user asks about forcing a draw by perpetual check or repetition.",
     "the user is worse and asks whether a perpetual draw exists.",
     ("Call best_move to see if a repeating checking line scores 0.",
      "Confirm the checks actually repeat the position.",
      "Give the first check of the perpetual."),
     "claim a perpetual only if the checks truly repeat."),
    ("stalemate-awareness",
     "Use when the user is winning and risks stalemating the enemy king.",
     "the user is up big material and asks how to finish safely.",
     ("Call board_state to check the opponent's legal_count.",
      "If the enemy is nearly stuck, leave it a legal move.",
      "Give a mating path that avoids stalemate."),
     "never give a move that stalemates while you are winning."),
    ("fianchetto-guide",
     "Use when the user asks about fianchetto setups and the long-diagonal bishop.",
     "the user asks how to set up or use a fianchettoed bishop.",
     ("Call board_state to see if the long diagonal is open.",
      "Plan the bishop's development and pawn shelter.",
      "Name the diagonal target the bishop eyes."),
     "keep the fianchetto pawns intact unless there is a concrete gain."),
    ("isolated-pawn-play",
     "Use when the user asks how to play with or against an isolated queen pawn.",
     "the user asks about an isolated pawn position.",
     ("Call board_state with fields=fen to confirm the isolani.",
      "Decide whether to blockade it or use its space.",
      "Give the plan for the side you are coaching."),
     "the isolani's owner attacks; the other side blockades."),
    ("open-file-strategy",
     "Use when the user asks how to use open or half-open files with rooks.",
     "the user asks about rooks, open files, or file control.",
     ("Call board_state with fields=fen to find open files.",
      "Plan to double rooks on the most useful file.",
      "Name the entry square the rooks aim for."),
     "contest a file only when you can win or hold it."),
    ("bishop-pair-coach",
     "Use when the user has two bishops and asks how to use the bishop pair.",
     "the user asks how to leverage the two bishops.",
     ("Call list_pieces to confirm both bishops are present.",
      "Plan to open the position for the bishops' range.",
      "Give the pawn break that frees them."),
     "open lines only when the bishops will outgun the knights."),
    ("knight-outpost",
     "Use when the user asks where to plant a knight or about outposts.",
     "the user asks about a strong knight square or outpost.",
     ("Call board_state with fields=fen to find a protected hole.",
      "Pick the square no enemy pawn can challenge.",
      "Give the route that lands the knight there."),
     "an outpost must be pawn-supported and unchallengeable."),
    ("back-rank-safety",
     "Use when the user asks about back-rank weaknesses or back-rank mates.",
     "the user asks if the back rank is safe or exploitable.",
     ("Call threats to test for a back-rank shot.",
      "If weak, find the move that exploits or defends it.",
      "Recommend luft or the mating move accordingly."),
     "verify the back-rank tactic with the engine before trusting it."),
    ("game-review",
     "Use when the user wants a full post-mortem of a game just played.",
     "the user asks to review the whole game or find where it went wrong.",
     ("Call review_move to grade the most recent move.",
      "Identify the moves where the evaluation swung most.",
      "Summarize the turning point and one lesson."),
     "grade moves from review_move output, not from memory."),
    ("board-recall",
     "Use when the user asks what the current board looks like, the FEN, or move history.",
     "the user asks to recall the board state, position, or history.",
     ("Call board_state with fields=all for turn, FEN, last move, check, history.",
      "Relay the facts the user asked for.",
      "Offer to evaluate or list legal moves next."),
     "report board facts only from board_state; never recite from memory."),
]
