"""Presentation deck — the STORY arc (GPU-free), matching the talk: meet the model → it's local →
small-but-thinks → how we trained it → the data → it floors out fast → (chats, shown live) → does it
work. This module renders only the FACTUAL / DATA visuals (pipeline+knobs, the think-loop diagram, the
real loss curve, the benchmark wins). The illustrative brand slides (meet-the-model, it's-local) are
AI-generated by the presenter from docs/report/slide-visuals.md. stat/curve helpers live in deck_stats,
the data chart in charts. `main()` renders the whole data set in one call.

Every number traces to a real artifact: hyperparameters from run_train.py; infra from memory
train-serve-infra-facts (Kaggle 2×T4 ×3 accounts ~135 GPU-h; serve Colab 1×T4); loss from
runs/full_train.log; benchmarks from docs/report/README.md §3. Nothing fabricated.
  python -m llm_training.report.deck [--out docs/findings/report_assets]"""
from __future__ import annotations

import argparse
from pathlib import Path

NAVY = "#1a2a4f"
GOLD = "#c8a24a"
# Real adapter routing confusion (gold rows -> predicted cols), native fair test, n=142 (README §3a).
ADAPTER_CM = {"skill": {"skill": 104, "tool": 7, "none": 6},
              "tool": {"skill": 0, "tool": 22, "none": 3},
              "none": {"skill": 0, "tool": 0, "none": 0}}
CM_CAPTION = ("Held-out val, n=142. Rows = the right call, columns = what it chose. The diagonal is "
              "126/142 = 88.7% correct\n(vs 49.6% for the un-tuned base). It rarely confuses "
              "“load a skill” with “call a tool.”")


def _plt():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    return plt


def _stage(ax, x, y, w, h, head, lines, fc, ec):
    from matplotlib.patches import FancyBboxPatch
    ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.012", fc=fc, ec=ec, lw=2.0))
    ax.text(x + w / 2, y + h * 0.74, head, ha="center", va="center", fontsize=12.5,
            fontweight="bold", color=ec)
    ax.text(x + w / 2, y + h * 0.34, "\n".join(lines), ha="center", va="center",
            fontsize=8.8, color="#333", linespacing=1.35)


def pipeline(out: Path) -> Path:
    """How we trained + serve it: 3-stage flow with the REAL infra, then the key knobs + why."""
    plt = _plt()
    fig, ax = plt.subplots(figsize=(11.5, 5.0)); fig.patch.set_facecolor("white")
    ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis("off")
    ax.text(0.5, 0.96, "How it was trained — and served", ha="center", fontsize=16,
            fontweight="bold", color=NAVY)
    stages = [("TRAIN", ["Kaggle 2× T4 (free)", "3 accounts · ~135 GPU-h", "over weeks"], "#dbe7f5", "#2471a3"),
              ("ADAPTER", ["tiny LoRA on top", "base stays frozen", "→ merge to serve"], "#d5f5e3", "#1e8449"),
              ("SERVE", ["Colab 1× T4 (live site)", "or local GGUF", "on your own GPU"], "#fadbd8", "#a93226")]
    w, gap, y, h = 0.27, 0.065, 0.52, 0.34
    for i, (head, lines, fc, ec) in enumerate(stages):
        x = 0.045 + i * (w + gap)
        _stage(ax, x, y, w, h, head, lines, fc, ec)
        if i < len(stages) - 1:
            ax.annotate("", (x + w + gap, y + h / 2), (x + w, y + h / 2),
                        arrowprops=dict(arrowstyle="-|>", lw=2.4, color="#888"))
    # the knobs + brief why (the "max seq, ranks, explain why" the script asks for)
    knobs = [("QLoRA · 4-bit nf4", "fit a 4B model on a free T4"),
             ("max seq 1664", "longest example is 1655 tok — don't truncate the reasoning"),
             ("rank 16 · all-linear", "enough to learn the format, small enough to fit"),
             ("loss-weight ×8 on tags", "the harness tags must beat the base model's habits")]
    ax.text(0.5, 0.40, "key settings (and why)", ha="center", fontsize=10.5,
            fontweight="bold", color=GOLD)
    yk = 0.32
    for name, why in knobs:
        ax.text(0.30, yk, name, ha="right", fontsize=9.5, fontweight="bold", color=NAVY)
        ax.text(0.33, yk, why, ha="left", fontsize=9.2, color="#555")
        yk -= 0.075
    fig.savefig(out, dpi=150, bbox_inches="tight"); plt.close(fig)
    print(f"wrote {out}", flush=True)
    return out


def thinks(out: Path) -> Path:
    """The harness contract — the FACTUAL loop (system_prompt.BASE_HARNESS): two verbs, exactly ONE
    action per step, then read the result and loop. NOT a fixed think→skill→tool chain."""
    plt = _plt()
    from matplotlib.patches import FancyArrowPatch, FancyBboxPatch
    fig, ax = plt.subplots(figsize=(11.0, 4.6)); fig.patch.set_facecolor("white")
    ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis("off")
    ax.text(0.5, 0.95, "How it works: two verbs, one action per step", ha="center", fontsize=16,
            fontweight="bold", color=NAVY)
    # the two verbs
    ax.add_patch(FancyBboxPatch((0.06, 0.50), 0.40, 0.26, boxstyle="round,pad=0.012",
                                fc="#d5f5e3", ec="#1e8449", lw=2.0))
    ax.text(0.26, 0.69, "<skill> NAME </skill>", ha="center", fontsize=12.5, fontweight="bold",
            color="#1e8449", family="DejaVu Sans Mono")
    ax.text(0.26, 0.585, "load a skill's guidance\n(instructions, not a function)", ha="center",
            va="center", fontsize=9.5, color="#222")
    ax.add_patch(FancyBboxPatch((0.54, 0.50), 0.40, 0.26, boxstyle="round,pad=0.012",
                                fc="#dbe7f5", ec="#2471a3", lw=2.0))
    ax.text(0.74, 0.69, "<tool> NAME args </tool>", ha="center", fontsize=12.5, fontweight="bold",
            color="#2471a3", family="DejaVu Sans Mono")
    ax.text(0.74, 0.585, "call a tool → get a result\n(data or a state change)", ha="center",
            va="center", fontsize=9.5, color="#222")
    # the loop: act -> read result -> act again (a return arc under the verb boxes)
    ax.add_patch(FancyArrowPatch((0.74, 0.50), (0.26, 0.50), connectionstyle="arc3,rad=-0.30",
                                 arrowstyle="-|>", lw=1.8, color="#bbb"))
    ax.text(0.5, 0.345, "pick ONE action  →  read the result  →  act again  →  …  →  grounded answer",
            ha="center", fontsize=11.5, color=NAVY, fontweight="bold")
    ax.text(0.5, 0.105, "It works like a coding agent — only the skills + tools LISTED in the prompt, "
            "which change every request.", ha="center", fontsize=10, color="#555")
    ax.text(0.5, 0.02, "Never invents a tool, never states a fact that isn't in a result.",
            ha="center", fontsize=10, color="#555", fontstyle="italic")
    fig.savefig(out, dpi=150, bbox_inches="tight"); plt.close(fig)
    print(f"wrote {out}", flush=True)
    return out


def modes(out: Path) -> Path:
    """The four reasoning modes the model was trained to switch between (system_prompt._REASONING_LINE).
    A small model that 'can't think' — taught to think only as much as the task needs."""
    plt = _plt()
    from matplotlib.patches import FancyBboxPatch
    fig, ax = plt.subplots(figsize=(11.2, 5.0)); fig.patch.set_facecolor("white")
    ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis("off")
    ax.text(0.5, 0.95, "Taught to think — only as much as the task needs", ha="center", fontsize=16,
            fontweight="bold", color=NAVY)
    cards = [
        ("FAST", "#aeb8c7", "no thinking —\nanswer directly", "“what's a fork?”"),
        ("THINK", "#2471a3", "<think> before\nEVERY step", "careful, show-the-work"),
        ("AUTO", "#1e8449", "<think> ONLY on\nthe hard choices", "the everyday default"),
        ("PLAN", "#c8a24a", "<goal> + a <plan>\nchecklist, do every box", "multi-step requests"),
    ]
    w, gap, y, h = 0.215, 0.025, 0.30, 0.42
    x0 = 0.5 - (4 * w + 3 * gap) / 2
    for i, (name, ec, what, ex) in enumerate(cards):
        x = x0 + i * (w + gap)
        ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.012", fc="white", ec=ec, lw=2.4))
        ax.text(x + w / 2, y + h - 0.06, name, ha="center", va="top", fontsize=14, fontweight="bold", color=ec)
        ax.text(x + w / 2, y + h * 0.50, what, ha="center", va="center", fontsize=10, color="#222")
        ax.text(x + w / 2, y + 0.05, ex, ha="center", va="center", fontsize=8.5,
                color="#666", fontstyle="italic")
    ax.text(0.5, 0.165, "Same model — it picks the mode from a signal in the prompt.",
            ha="center", fontsize=11, color="#333")
    ax.text(0.5, 0.075, "A 4B model that isn't a natural reasoner — we trained the reasoning IN, "
            "and the restraint to not over-think.", ha="center", fontsize=10, color="#555")
    fig.savefig(out, dpi=150, bbox_inches="tight"); plt.close(fig)
    print(f"wrote {out}", flush=True)
    return out


def main() -> None:
    from llm_training.report import chart_data as D, charts, deck_stats as S, ppt_charts
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(D.REPO / "docs" / "findings" / "report_assets"))
    args = ap.parse_args()
    o = Path(args.out); o.mkdir(parents=True, exist_ok=True)
    st = D.corpus_stats()
    # Files are NUMBERED by talk position (see docs/report/slide-visuals.md) so they sort in
    # presentation order and interleave with the presenter's slides: 01-02 = AI-gen brand
    # (meet-the-model, it's-local), 07 = the live chats (presenter supplies). This renders only the
    # FACTUAL / DATA visuals.
    # 03 · the contract: two verbs, one action per step (the FACTUAL loop)
    thinks(o / "03-how-it-works.png")
    # 03b · the four reasoning modes (fast / think / auto / plan)
    modes(o / "03b-reasoning-modes.png")
    # 04 · how trained + served (real knobs + infra)
    pipeline(o / "04-how-trained.png")
    # 05 · the data (slices + mode mix)
    charts.corpus_composition(st, o / "05-the-data.png")
    # 06 · floors out fast (REAL loss curve)
    losses = D.load_train_losses()
    if losses:
        S.floors_out(losses, o / "06-floors-out.png", st["n_train"])
    else:
        print("no runs/full_train.log -> skipping floors-out slide (no fabricated curve)", flush=True)
    # 7 · (chats shown live from the Kaggle run) — not rendered here
    # 8 · does it work — TWO results, framed as TWO DIFFERENT QUESTIONS so they don't read as
    # comparable. EXACT numbers (88.7 / 91.7), never rounded, so they match the confusion backup and
    # don't look fudged. The 55->7 / F1 detail lives ONLY on the confusion backup (no redundant slide).
    S.big_compare("49.6%", "88.7%", "base model", "after fine-tuning",
                  "Q1 · Does it pick the right action?  (routing)",
                  "Held-out chess val, n=142. The base over-fired tools (55 false-calls → 7); the "
                  "fine-tune taught it when to load a skill vs call a tool.", o / "08-result-routing.png")
    S.big_single("91.7%", "Q2 · Can it finish a task in a domain it never trained on?",
                 "tasks completed on real cooking / music / wellness / tax prompts (n=60, 95% grounded) — "
                 "a DIFFERENT test from Q1, so this isn't a drop from 88.7%.",
                 ["cooking", "music", "wellness", "tax"], o / "09-result-generalizes.png")
    # BACKUP only (not in the main flow): the per-class proof. Same 88.7% as the routing slide.
    ppt_charts.confusion_matrix(ADAPTER_CM, ["skill", "tool", "none"], o / "backup-confusion.png",
                                CM_CAPTION, title="Where it routes right — E4B v4 adapter (val)")
    print(f"\nStory deck rendered into {o}", flush=True)


if __name__ == "__main__":
    main()
